name: Deploy to Render

on:
  # Se activa cuando se hace push directo a main/master
  push:
    branches: [ main, master ]
  
  # O cuando el workflow de pruebas en PR se completa exitosamente
  workflow_run:
    workflows: ["Test and Deploy"]
    types: [completed]
    branches: [main, master]

jobs:
  deploy:
    # Solo ejecutar si es un push directo o si el workflow de pruebas fue exitoso
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Render using API
      run: |
        # Trigger a new deployment using Render's API
        curl -X POST \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
          -H 'Accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{"clearCache": "do_not_clear"}'
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        renderYmlPath: ./render.yaml
